-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: JWTAuth.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE jwtauth (
  jwtauth_user INT NOT NULL,
  jwtauth_subject TEXT NOT NULL,
  jwtauth_issuer TEXT NOT NULL,
  PRIMARY KEY(jwtauth_user)
);

CREATE INDEX jwtauth_subject ON jwtauth (jwtauth_subject, jwtauth_issuer);
