-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: JWTAuth.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/jwtauth (
  jwtauth_user INTEGER UNSIGNED NOT NULL,
  jwtauth_subject BLOB NOT NULL,
  jwtauth_issuer BLOB NOT NULL,
  PRIMARY KEY(jwtauth_user)
);

CREATE INDEX jwtauth_subject ON /*_*/jwtauth (jwtauth_subject, jwtauth_issuer);
