-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: JWTAuth.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/jwtauth (
  jwtauth_user INT UNSIGNED NOT NULL,
  jwtauth_subject TINYBLOB NOT NULL,
  jwtauth_issuer TINYBLOB NOT NULL,
  INDEX jwtauth_subject (
    jwtauth_subject(50),
    jwtauth_issuer(50)
  ),
  PRIMARY KEY(jwtauth_user)
) /*$wgDBTableOptions*/;
